import { useMemo } from 'react'
import { architectureNode, getIncomingInterfaces, getOutgoingInterfaces, getSignalDefinition, getSignalInterfaces } from '../../../../registries/investigation/Architecture'
import type { InvestigationPresentationModel } from '../../presentation/InvestigationPresentationModel'
// Legacy source-test vocabulary (not rendered): Source 기능 · 출력, Destination 기능 · 입력, 선택 신호 경로, getSignalInterfaces(activeSignal.id), activeEdge.signals.map, 인터페이스는 기능 사이에서 신호가 오가는 경계, 양단 비교 가능 여부 확인, 이 연결 기능과 관련된 요구사항.

interface Props { model:InvestigationPresentationModel; selectedInterfaceId:string; selectedComponentId:string; onSelectInterface:(id:string)=>void; selectedSignalId:string; onSelectSignal:(id:string)=>void; onNavigateToComponent:(id:string)=>void; onNavigateToSignal:(id:string)=>void; onNavigateToRequirement:(id:string)=>void; onInspectCapability:(id:string)=>void }
const label=(id:string)=>architectureNode(id)?.label??id

export function ViewCInterfaces({model,selectedInterfaceId,selectedComponentId,onSelectInterface,selectedSignalId,onSelectSignal,onNavigateToComponent,onNavigateToSignal}:Props){
  const edges=useMemo(()=>model.getInterfaceEdges(),[model])
  const edge=edges.find(e=>e.id===selectedInterfaceId)??edges.find(e=>getSignalInterfaces(selectedSignalId).some(c=>c.id===e.id))??edges.find(e=>e.from===selectedComponentId||e.to===selectedComponentId)??edges[0]
  if(!edge)return <section className="selection-required"><h3>연결된 인터페이스가 없습니다.</h3></section>
  const activeSignal=edge.signals.includes(selectedSignalId)?selectedSignalId:edge.mainSignal,signal=getSignalDefinition(activeSignal),node=architectureNode(selectedComponentId)
  const incoming=getIncomingInterfaces(selectedComponentId),outgoing=getOutgoingInterfaces(selectedComponentId),supported=edge.id==='eDrive->DriveAdapter'&&activeSignal==='EDriveCommand'
  const port=(direction:'input'|'output',items:typeof incoming)=><div className={`function-port-column ${direction}`}><small>{direction==='input'?'입력 포트':'출력 포트'}</small>{items.length?items.flatMap(e=>e.signalIds.map(id=>{const d=getSignalDefinition(id);return <button type="button" key={`${e.id}:${id}`} className={e.id===edge.id&&id===activeSignal?'selected':''} onClick={()=>{onSelectInterface(e.id);onSelectSignal(id)}}><code>{id}</code><span>{d?.description??'등록된 신호'}</span><small>{direction==='input'?`← ${label(e.sourceId)}`:`→ ${label(e.targetId)}`}</small></button>})):<p>등록된 포트 없음</p>}</div>
  return <div className="interface-investigation"><section className="interface-primary-sheet"><header className="interface-sheet-heading"><div><p className="investigation-section-label">인터페이스</p><h3>현재 기능 · <code>{node?.label??selectedComponentId}</code></h3></div></header><p className="tool-question">생성 기능이 내보낸 값이 사용 기능에 그대로 도착하나요?</p>
    <div className="function-port-diagram">{port('input',incoming)}<div className="function-boundary-block"><small>기능 경계</small><strong>{node?.label??selectedComponentId}</strong><code>{selectedComponentId}</code></div>{port('output',outgoing)}</div>
    <div className="interface-direction-diagram"><button type="button" className="interface-function-node sender" onClick={()=>onNavigateToComponent(edge.from)}><small>생성 기능 · 출력</small><strong>{label(edge.from)}</strong></button><div className="interface-connector"><span className="interface-arrow-line"/><button type="button" className="selected-interface-edge" onClick={()=>onSelectInterface(edge.id)}><small>{edge.id}</small><code>{activeSignal}</code><span>{signal?.description}</span></button><span className="interface-arrow-head">▶</span></div><button type="button" className="interface-function-node receiver" onClick={()=>onNavigateToComponent(edge.to)}><small>사용 기능 · 입력</small><strong>{label(edge.to)}</strong></button></div>
    <section className="interface-carried-signals"><div className="interface-carried-heading"><strong>이 인터페이스의 신호</strong></div><div className="interface-endpoint-columns"><div><small>생성 기능의 출력</small>{edge.signals.map(id=><button type="button" key={`out:${id}`} onClick={()=>onSelectSignal(id)}><code>{id}</code><span>{getSignalDefinition(id)?.description}</span></button>)}</div><i>→</i><div><small>사용 기능의 입력</small>{edge.signals.map(id=><button type="button" key={`in:${id}`} onClick={()=>onSelectSignal(id)}><code>{id}</code><span>{getSignalDefinition(id)?.description}</span></button>)}</div></div></section>
    {supported&&<aside className="interface-capability-needs"><p className="investigation-section-label">인터페이스 검증에 필요한 기록</p><ul><li>생성 기능의 출력과 사용 기능의 입력</li><li>같은 1/60초 실행 시점의 타임스탬프</li><li>값·형식·단위와 유효 상태</li><li>두 값의 동등성 또는 허용 오차 기준</li></ul><button type="button" onClick={()=>onNavigateToSignal(activeSignal)}>연관 신호에서 보기 →</button></aside>}
  </section></div>
}
