import { useEffect, useMemo, useState } from 'react'
import type { CSSProperties, MouseEvent } from 'react'
import type { IncidentFrame } from '../../../../runtime/case/PropulsionCase'
import type { SignalDefinition, SignalValue } from '../../../../registries/investigation/Architecture'
import { architectureNode, getInputSignals, getOutputSignals, getSignalDefinition, getSignalInterfaces, getSignalObservation, getSignalTimelineCapability } from '../../../../registries/investigation/Architecture'
// Regression vocabulary retained for source-level compatibility: 판정 기준 미지원, 단위별 독립 스케일, difference-region, event-marker, selected-time-marker, 근거에 추가.

interface Props { selectedComponent:string; selectedSignal:string; onSelectSignal:(id:string)=>void; currentFrame:IncidentFrame|undefined; frames:readonly IncidentFrame[]; onSelectFrameIndex:(i:number)=>void; onCompareSignal:(id:string)=>void; onSaveAsEvidence:(id:string)=>void; onNavigateToStandards:()=>void; onNavigateToInterfaces:()=>void; onNavigateToComponent:(id:string)=>void }
const format=(v:SignalValue|undefined)=>v==null?'—':typeof v==='number'?v.toFixed(3):typeof v==='boolean'?(v?'TRUE':'FALSE'):typeof v==='object'?JSON.stringify(v):String(v)
const colors=['#b45c37','#315d8a','#7a5b99','#7a6b24','#2f7664','#9a4b67']

export function ViewBSignals(p:Props){
  const inputs=useMemo(()=>getInputSignals(p.selectedComponent),[p.selectedComponent]),outputs=useMemo(()=>getOutputSignals(p.selectedComponent),[p.selectedComponent])
  const states=inputs.filter(s=>s.semanticRole==='STATE_OR_PRECONDITION'),values=inputs.filter(s=>s.semanticRole!=='STATE_OR_PRECONDITION')
  const available=useMemo(()=>[...new Map([...states,...values,...outputs].map(s=>[s.id,s])).values()],[states,values,outputs])
  const selected=getSignalDefinition(p.selectedSignal)??outputs[0]??inputs[0]
  const [visibleIds,setVisibleIds]=useState<string[]>([]),[savedSignal,setSavedSignal]=useState('')
  useEffect(()=>{const defaults=[states[0]?.id,values[0]?.id,selected?.id,outputs[0]?.id].filter((id):id is string=>Boolean(id));setVisibleIds(ids=>{const retained=ids.filter(id=>available.some(s=>s.id===id));return [...new Set(retained.length?retained:defaults)]})},[p.selectedComponent]) // eslint-disable-line react-hooks/exhaustive-deps
  useEffect(()=>{if(selected&&!visibleIds.includes(selected.id))setVisibleIds(ids=>[...ids,selected.id])},[selected?.id]) // eslint-disable-line react-hooks/exhaustive-deps
  const selectedIndex=Math.max(0,p.currentFrame?p.frames.findIndex(f=>f.id===p.currentFrame?.id):0),observation=p.currentFrame&&selected?getSignalObservation(selected.id,p.currentFrame,p.frames[selectedIndex-1]):undefined
  const interfaces=selected?getSignalInterfaces(selected.id):[],visible=available.filter(s=>visibleIds.includes(s.id))
  const setGroup=(items:SignalDefinition[],show:boolean)=>setVisibleIds(ids=>show?[...new Set([...ids,...items.map(i=>i.id)])]:ids.filter(id=>!items.some(i=>i.id===id)))
  const group=(title:string,items:SignalDefinition[])=><section className="monitor-signal-group always-open"><header><b>{title}</b><span>{items.length}개</span><span className="monitor-group-actions"><button type="button" onClick={()=>setGroup(items,true)}>전체 선택</button><button type="button" onClick={()=>setGroup(items,false)}>전체 해제</button></span></header>{items.length?items.map(signal=><label key={signal.id}><input type="checkbox" checked={visibleIds.includes(signal.id)} onChange={()=>setVisibleIds(ids=>ids.includes(signal.id)?ids.filter(id=>id!==signal.id):[...ids,signal.id])}/><button type="button" aria-pressed={selected?.id===signal.id} onClick={()=>{p.onSelectSignal(signal.id);p.onCompareSignal(signal.id)}}><code>{signal.id}</code><small>{signal.description}</small></button></label>):<p>등록된 관측 신호 없음</p>}</section>
  return <div className="signal-monitor-workspace">
    <section className="monitor-heading"><div><p className="investigation-section-label">연관 신호 · 사건 신호 비교</p><h3>현재 기능 · <code>{architectureNode(p.selectedComponent)?.label??p.selectedComponent}</code></h3></div><p className="tool-question">어느 신호에서 처음 차이가 생기나요?</p></section>
    <div className="monitor-signal-groups">{group('A. 전제조건 / 상태',states)}{group('B. 기능 입력',values)}{group('C. 기능 출력',outputs)}</div>
    {selected&&<section className="signal-identity-card"><header><div><p className="investigation-section-label">선택 신호의 역할</p><h3>{selected.description??selected.label}</h3></div><code>{selected.id}</code></header><div className="signal-path-strip"><span><small>생성</small>{selected.producerIds.map(id=>architectureNode(id)?.label??id).join(' · ')||'운전자/차량 상태'}</span><i>→</i><span><small>전달</small><code>{selected.id}</code></span><i>→</i><span><small>사용</small>{selected.consumerIds.map(id=>architectureNode(id)?.label??id).join(' · ')||'차량 반응'}</span></div></section>}
    <SynchronizedTimeline frames={p.frames} signals={visible} selectedIndex={selectedIndex} onSelectFrame={p.onSelectFrameIndex}/>
    <div className="monitor-lower-grid"><section className="monitor-signal-detail"><p className="investigation-section-label">선택 신호</p><h3><code>{selected?.id??'—'}</code></h3><p className="investigation-prose">{selected?.description??'등록된 설명 없음'}</p><p><b>현재 관찰값</b> · {format(observation?.actual.value)}{selected?.unit?` ${selected.unit}`:''}</p><div className="evidence-save-control"><button type="button" className="save-comparison-button" onClick={()=>{if(selected){p.onSaveAsEvidence(selected.id);setSavedSignal(selected.id)}}}>이 관찰을 조사 노트에 기록</button>{savedSignal===selected?.id&&<small>✓ 기록됨</small>}</div></section>
      <aside className="adjacent-observation-guide"><p className="investigation-section-label">다음 조사</p><h3>인접 값 확인</h3><div>{selected?.producerIds.map(id=><button type="button" key={`p:${id}`} onClick={()=>p.onNavigateToComponent(id)}>생성 기능 · {architectureNode(id)?.label??id}</button>)}{selected?.consumerIds.map(id=><button type="button" key={`c:${id}`} onClick={()=>p.onNavigateToComponent(id)}>사용 기능 · {architectureNode(id)?.label??id}</button>)}{interfaces.length>0&&<button type="button" onClick={p.onNavigateToInterfaces}>인터페이스 보기</button>}<button type="button" onClick={p.onNavigateToStandards}>요구사항 보기</button></div></aside></div>
  </div>
}

function SynchronizedTimeline({frames,signals,selectedIndex,onSelectFrame}:{frames:readonly IncidentFrame[];signals:SignalDefinition[];selectedIndex:number;onSelectFrame:(index:number)=>void}){
  const [hover,setHover]=useState<{index:number;row:number}|null>(null)
  const width=820,left=178,right=18,rowHeight=82,top=18,bottom=30,height=Math.max(156,top+signals.length*rowHeight+bottom),x=(i:number)=>left+(i/Math.max(1,frames.length-1))*(width-left-right)
  const locate=(e:MouseEvent<SVGSVGElement>)=>{const r=e.currentTarget.getBoundingClientRect(),sx=(e.clientX-r.left)/r.width*width,sy=(e.clientY-r.top)/r.height*height;return {index:Math.round(Math.max(0,Math.min(1,(sx-left)/(width-left-right)))*Math.max(0,frames.length-1)),row:Math.max(0,Math.min(signals.length-1,Math.floor((sy-top)/rowHeight)))}}
  const hoverFrame=hover?frames[hover.index]:undefined,hoverSignal=hover?signals[hover.row]:undefined,hoverValue=hoverFrame&&hoverSignal?getSignalObservation(hoverSignal.id,hoverFrame,frames[Math.max(0,hover!.index-1)]):undefined
  return <section className="monitor-timeline-sheet"><header><div><p className="investigation-section-label">통합 신호 분석</p><h3>하나의 시간축에서 비교</h3></div><div className="monitor-legend"><span className="actual">Actual</span><span className="expected">Expected</span><span className="cursor">선택 시점</span></div></header>{signals.length?<div className="monitor-plot-wrap"><svg viewBox={`0 0 ${width} ${height}`} onClick={e=>onSelectFrame(locate(e).index)} onMouseMove={e=>setHover(locate(e))} onMouseLeave={()=>setHover(null)}>{signals.map((s,row)=><Track key={s.id} signal={s} frames={frames} row={row} x={x} width={width} left={left} right={right} top={top} rowHeight={rowHeight}/>)}<line className="monitor-cursor" x1={x(selectedIndex)} x2={x(selectedIndex)} y1={top} y2={height-bottom}/>{hover&&<line className="monitor-hover-line" x1={x(hover.index)} x2={x(hover.index)} y1={top} y2={height-bottom}/>}<text className="monitor-axis-label" x={left} y={height-8}>{frames[0]?.sw.executionTime.toFixed(3)??'0.000'} s</text><text className="monitor-axis-label" x={width-right} y={height-8} textAnchor="end">{frames.at(-1)?.sw.executionTime.toFixed(3)??'0.000'} s</text></svg>{hoverFrame&&hoverSignal&&<div className="monitor-hover-readout"><b>{hoverFrame.sw.executionTime.toFixed(3)} s</b><span><code>{hoverSignal.id}</code> {format(hoverValue?.actual.value)}{hoverSignal.unit?` ${hoverSignal.unit}`:''}</span></div>}</div>:<div className="monitor-empty-track">위에서 표시할 신호를 선택하세요.</div>}</section>
}

function Track({signal,frames,row,x,left,right,width,top,rowHeight}:{signal:SignalDefinition;frames:readonly IncidentFrame[];row:number;x:(i:number)=>number;left:number;right:number;width:number;top:number;rowHeight:number}){
  const obs=frames.map((f,i)=>getSignalObservation(signal.id,f,frames[i-1])),actual=obs.map(o=>o.actual.value),expected=obs.map(o=>o.expected?.value),capability=getSignalTimelineCapability(signal.id,frames),yTop=top+row*rowHeight+15,yBottom=yTop+42
  const nums=[...actual,...expected].filter((v):v is number=>typeof v==='number'),min=nums.length?Math.min(...nums):0,max=nums.length?Math.max(...nums):1,span=max-min||1,y=(v:number)=>yTop+(max-v)/span*(yBottom-yTop)
  const points=(series:(SignalValue|undefined)[])=>series.map((v,i)=>typeof v==='number'?`${x(i)},${y(v)}`:null).filter(Boolean).join(' ')
  const categories=[...new Set([...actual,...expected].filter(v=>typeof v==='string'||typeof v==='boolean').map(String))],stateY=(v:SignalValue|undefined)=>yTop+(Math.max(0,categories.indexOf(String(v)))/Math.max(1,categories.length-1))*(yBottom-yTop),step=(series:(SignalValue|undefined)[])=>series.reduce<string>((p,v,i)=>v==null?p:!p?`M ${x(i)} ${stateY(v)}`:`${p} H ${x(i)} V ${stateY(v)}`,'')
  return <g className="monitor-track" style={{'--series-color':colors[row%colors.length]} as CSSProperties}><rect x="0" y={top+row*rowHeight} width={width} height={rowHeight-4}/><text className="monitor-track-id" x="8" y={yTop}>{signal.id}</text><text className="monitor-track-unit" x="8" y={yTop+18}>{signal.description}</text><line className="monitor-track-baseline" x1={left} x2={width-right} y1={yBottom} y2={yBottom}/>{nums.length?<><polyline className="monitor-actual-line" points={points(actual)}/>{capability==='COMPARE_TIMELINE'&&<polyline className="monitor-expected-line" points={points(expected)}/>}</>:<><path className="monitor-state-line" d={step(actual)}/>{capability==='COMPARE_TIMELINE'&&<path className="monitor-expected-state" d={step(expected)}/>}</>}</g>
}
