import { useState } from 'react'
import { useCase } from '../state/CaseContext'
import { failureTypes } from '../../runtime/investigation/CaseDefinition'
import { architectureNode } from '../../registries/investigation/Architecture'
import { propulsionRequirements } from '../../data/ground-truth/PropulsionGroundTruth'
import { ExperimentResults } from '../screens/CaseExperimentPanel'
import type { Evidence } from '../../runtime/investigation/Evidence'
import { inspectBoundary } from '../../runtime/investigation/Boundary'

const swComponents=['GearLogic','PropulsionFunction','VMC','eDrive']
const failureLabels:Record<string,string>={LOGIC_CALCULATION:'논리 · 계산 오류',STATE_MODE:'상태 · 모드 오류',INTERFACE_SIGNAL:'인터페이스 · 신호 오류',TIMING_EXECUTION:'타이밍 · 실행 오류',DATA_CALIBRATION:'데이터 · 보정값 오류',FAULT_HANDLING_MONITORING:'고장 대응 · 감시 오류'}
function EvidenceContent({e}:{e:Evidence}){const {state}=useCase(),frame=state.frames.find(item=>item.id===e.reference.frameId),run=state.experiments.find(item=>item.id===e.reference.runId),boundary=frame?inspectBoundary(frame,e.relatedComponent):null;return <span><b>{e.type==='TEST_RESULT'?'재현 시험 결과':e.type==='SIGNAL_BOUNDARY'?'주행 신호 비교':e.type==='REQUIREMENT'?'요구사항':'시험 기준'} · {architectureNode(e.relatedComponent).label}</b>{boundary&&<small>기대 {JSON.stringify(boundary.expected)} / 실제 {JSON.stringify(boundary.actual)}</small>}{run?.rows.map(row=><small key={row.id}>입력 {row.input} → 기대 {row.expected} / 실제 {row.actual} · {row.pass?'일치':'불일치'}</small>)}{e.relatedRequirementIds.map(id=><small key={id}><code>{id}</code> {propulsionRequirements.find(req=>req.id===id)?.statement}</small>)}</span>}
function EvidenceList(){const {controller,state}=useCase();return <div className="evidence-list">{state.evidence.length?state.evidence.map(e=><label className="evidence-note" key={e.id}><input type="checkbox" checked={e.selectedForReport} disabled={!!state.diagnosis} onChange={event=>controller.selectEvidence(e.id,event.target.checked)}/><EvidenceContent e={e}/></label>):<p>주행 신호 비교나 재현 시험을 실행하면, 이곳에서 제출 근거를 선택할 수 있습니다.</p>}</div>}

export function RootCauseReportPanel(){
 const {controller,state}=useCase(),[location,setLocation]=useState(''),[type,setType]=useState(''),[cause,setCause]=useState(''),[repair,setRepair]=useState<0|2|3>(0),[error,setError]=useState('')
 const selected=state.evidence.filter(item=>item.selectedForReport)
 const tcIds=[...new Set(selected.flatMap(item=>item.relatedTestCaseIds))]
 const reqIds=[...new Set(selected.flatMap(item=>item.relatedRequirementIds))]
 const submit=()=>{try{controller.submitReport({faultLocation:location,failureType:type,detailedCause:cause,evidenceIds:selected.map(item=>item.id)});setError('')}catch(reason){setError(String(reason))}}
 if(state.diagnosis)return <SubmittedReport repair={repair} setRepair={setRepair}/>
 return <section className="root-cause-workspace"><article className="root-cause-form"><header><div><small>원인 분석</small><h3>원인 후보를 구성하세요</h3></div><span>제출 전에는 실제 원인이 공개되지 않습니다.</span></header><section className="root-function-picker"><h4>1 · 원인 기능 선택</h4><div className="root-architecture"><span>Driver Demand</span><i>→</i><div>{swComponents.map(id=><button key={id} aria-pressed={location===id} onClick={()=>setLocation(id)}>{architectureNode(id).label}</button>)}</div><i>→</i><span>Vehicle Action</span></div></section><section><h4>2 · 관련 요구사항 · 검증 기준</h4><p className="selection-summary">선택한 근거에서 요구사항과 TC가 자동으로 연결됩니다.</p><div className="selected-trace">{reqIds.length?reqIds.map(id=><p key={id}><code>{id}</code><span>{propulsionRequirements.find(req=>req.id===id)?.statement}</span></p>):<p>아직 선택한 근거가 없습니다.</p>}{tcIds.map(id=><p key={id}><code>{id}</code><span>검증에 사용한 시험 기준</span></p>)}</div></section><section className="failure-picker"><h4>3 · 오류 분류 선택</h4><div>{failureTypes.map(item=><button key={item.id} aria-pressed={type===item.id} onClick={()=>{setType(item.id);setCause('')}}>{failureLabels[item.id]??item.label}</button>)}</div>{type&&<div className="cause-picker">{failureTypes.find(item=>item.id===type)?.causes.map(item=><button key={item.id} aria-pressed={cause===item.id} onClick={()=>setCause(item.id)}>{item.label.split(' · ').at(-1)}</button>)}</div>}</section><section><h4>4 · 판단 근거 선택</h4><EvidenceList/></section><button className="primary navigation-action submit-report" disabled={!location||!type||!cause||!selected.length} onClick={submit}>원인 분석 제출 →</button>{!selected.length&&<small className="submit-hint">주행 신호 비교 또는 재현 시험 결과를 한 개 이상 선택해야 합니다.</small>}{error&&<p role="alert">{error}</p>}</article><article className="report-preview"><h3>분석 보고서</h3><div className="report-empty"><span>🐱</span><b>제출하면 분석 보고서가 발행됩니다.</b><p>선택한 기능, 요구사항, 시험 근거를 바탕으로 판정 결과를 확인할 수 있습니다.</p></div></article></section>
}
function SubmittedReport({repair,setRepair}:{repair:0|2|3;setRepair:(value:0|2|3)=>void}){const {controller,state}=useCase(),diagnosis=state.diagnosis!,isVerified=diagnosis.correct&&diagnosis.evidenceSufficient;const selected=state.evidence.filter(item=>item.selectedForReport);return <section className="submitted-report"><article className="report-summary"><small>TRACKBACK</small><h3>고장 원인 분석 보고서</h3><code>{controller.definition.id}</code><dl><div><dt>사건</dt><dd>{controller.definition.title}</dd></div><div><dt>제출 기능</dt><dd>{architectureNode(diagnosis.component).label}</dd></div><div><dt>오류 분류</dt><dd>{failureLabels[diagnosis.report?.failureType??'']??diagnosis.mechanism}</dd></div><div><dt>첨부 근거</dt><dd>{selected.length}개</dd></div></dl><div className={`report-stamp ${isVerified?'verified':'unverified'}`}>{isVerified?'원인 확인':'원인 미확인'}</div>{isVerified?<><h4>실제 원인</h4><p>{controller.definition.rootCause.explanation}</p></>:<p>제출한 기능 또는 오류 분류가 확인되지 않았거나, 반복 시험 근거가 부족합니다. 주행 신호와 재현 시험 결과를 다시 확인해보세요.</p>}<h4>근거 요약</h4>{selected.map(item=><div className="report-evidence-row" key={item.id}><EvidenceContent e={item}/></div>)}</article><article className="repair-sheet"><h3>수정 검증</h3><p>원인 제출 뒤에만 기존 독립 C 시험으로 수정안을 확인할 수 있습니다.</p><select aria-label="수정안" value={repair} onChange={event=>setRepair(Number(event.target.value) as 0|2|3)} disabled={state.phase==='RESOLVED'}><option value={0}>비율 감소 제거 · 방향별 제한 유지</option><option value={2}>입력 요청을 두 배로 보상</option><option value={3}>출력 상한 제한 해제</option></select><button className="primary navigation-action" disabled={state.phase==='RESOLVED'} onClick={()=>controller.runRepair(repair)}>수정안 시험 실행 →</button>{state.repairs.map(run=><details key={run.id}><summary>수정 시험 #{run.id} · {run.rows.every(row=>row.pass)?'PASS':'FAIL'}</summary><ExperimentResults run={run}/></details>)}<p>{state.phase==='RESOLVED'?'수정 검증 완료 · 주행을 재개할 수 있습니다.':'수정 검증 결과를 확인해보세요.'}</p></article></section>}
