import { useMemo, useState } from 'react'
import type { Evidence, RootCauseReport } from '../../../runtime/investigation/Evidence'
import type { Diagnosis, ExperimentRun, IncidentFrame } from '../../../runtime/case/PropulsionCase'
import type { CaseDefinition } from '../../../runtime/investigation/CaseDefinition'
import type { HypothesisModel } from '../presentation/InvestigationPresentationModel'
import { failureTypes } from '../../../runtime/investigation/CaseDefinition'
import { assessEvidence } from '../../../runtime/investigation/Assessment'
import { architectureNode, architectureNodes } from '../../../registries/investigation/Architecture'
import { ExperimentResults } from '../../screens/CaseExperimentPanel'

interface Props { definition:CaseDefinition; hypothesis:HypothesisModel|null; evidenceList:readonly Evidence[]; frames:readonly IncidentFrame[]; experiments:readonly ExperimentRun[]; diagnosis:Diagnosis|null; repairs:readonly ExperimentRun[]; resolved:boolean; onSelectEvidenceForReport:(id:string,selected:boolean)=>void; onSubmitReport:(report:RootCauseReport)=>void; onRunRepair:(variant:0|2|3)=>void; onNavigateToDebrief?:()=>void; onStartGuidedReview:()=>void; onRetryInvestigation:()=>void }
const targets=['GearLogic','PropulsionFunction','VMC','eDrive','DriveAdapter','VehiclePhysics']
const failureCopy:Record<string,{title:string;description:string}>={LOGIC_CALCULATION:{title:'논리 / 계산',description:'계산식, 제한값 적용 또는 방향 처리 오류'},STATE_MODE:{title:'상태 / 모드',description:'상태 전이 또는 활성 조건 판단 오류'},INTERFACE_SIGNAL:{title:'인터페이스 / 신호',description:'기능 사이 신호 전달 또는 매핑 오류'},TIMING_EXECUTION:{title:'타이밍 / 실행',description:'호출 시점, 주기 또는 실행 누락 문제'},DATA_CALIBRATION:{title:'데이터 / Calibration',description:'보정 데이터 또는 기준값 설정 문제'},FAULT_HANDLING_MONITORING:{title:'감시 / 고장 처리',description:'진단 감시와 고장 반응 조건 문제'}}
const evidenceLabel=(item:Evidence)=>item.type==='SIGNAL_COMPARISON'?'신호 비교':item.type==='SIGNAL_OBSERVATION'?'신호 관찰':item.type==='SIGNAL_BOUNDARY'?'기능 경계 비교':item.type==='INTERFACE_COMPARISON'?'인터페이스 양단 비교':item.type==='REQUIREMENT'?'요구사항 기준':item.type==='TEST_RESULT'?'재현 시험':item.type==='INCIDENT_FRAME'?'사건 시점 기록':item.type
const evidenceRank=(item:Evidence)=>item.type==='INCIDENT_FRAME'?0:item.type.startsWith('SIGNAL')?1:item.type==='INTERFACE_COMPARISON'?2:item.type==='REQUIREMENT'?3:item.type==='TEST_RESULT'?4:5

export function Page4Conclusion({definition,hypothesis,evidenceList,frames,experiments,diagnosis,repairs,resolved,onSelectEvidenceForReport,onSubmitReport,onRunRepair,onNavigateToDebrief,onStartGuidedReview,onRetryInvestigation}:Props){
  const [target,setTarget]=useState('')
  const [failureType,setFailureType]=useState('')
  const [cause,setCause]=useState('')
  const [error,setError]=useState('')
  const [showRepair,setShowRepair]=useState(false)
  const [repair,setRepair]=useState<0|2|3>(0)
  const verificationEvidence=evidenceList.filter(item=>item.type==='TEST_RESULT')
  const investigationNotes=evidenceList.filter(item=>item.type!=='TEST_RESULT')
  const selected=evidenceList.filter(item=>item.selectedForReport)
  const selectedPrimary=verificationEvidence.filter(item=>item.selectedForReport)
  const selectedNotes=investigationNotes.filter(item=>item.selectedForReport)
  const assessment=useMemo(()=>assessEvidence(definition,selectedPrimary,frames,experiments),[definition,selectedPrimary,frames,experiments])
  const detailedUnlocked=assessment.sufficient
  const failure=failureTypes.find(item=>item.id===failureType)
  const candidateNodes=architectureNodes.filter(node=>targets.includes(node.id))
  const orderedNotes=[...investigationNotes].sort((a,b)=>evidenceRank(a)-evidenceRank(b))
  const supportedComponents=[...new Set(selected.filter(item=>item.status==='MISMATCH').map(item=>item.relatedComponent))]
  const submit=()=>{if(!target||!failureType||!selectedPrimary.length){setError('원인 위치, 문제 유형, 검증 근거를 확인하세요.');return}if(!assessment.sufficient){setError('현재 선택한 검증 근거만으로는 이 진단 수준을 제출할 수 없습니다. 추가 검증을 진행하세요.');return}try{onSubmitReport({faultLocation:target,failureType,detailedCause:detailedUnlocked&&cause?cause:undefined,evidenceIds:[...selectedPrimary,...selectedNotes].map(item=>item.id)});setError('')}catch(reason){setError(String(reason))}}

  if(diagnosis){const solved=diagnosis.correct&&diagnosis.evidenceSufficient;const locationOnly=diagnosis.correct&&!diagnosis.evidenceSufficient;return <div className="investigation-main-content conclusion-result-page">
    <section className={`diagnosis-result-stamp ${solved?'correct':locationOnly?'partial':'wrong'}`}><small>{solved?'CASE SOLVED':locationOnly?'LOCATION IDENTIFIED':'RECHECK'}</small><strong>{solved?'근거 충분 · 진단 완료':locationOnly?'원인 위치 좁힘 · 추가 검증 필요':'조금 더 확인해볼까요?'}</strong></section>
    <div className="diagnosis-two-results"><section><p className="investigation-section-label">진단 정확성</p><b className={diagnosis.correct?'pass':'fail'}>{diagnosis.correct?'제출한 위치와 유형이 일치':'제출한 원인과 사건 데이터 불일치'}</b></section><section><p className="investigation-section-label">근거 충분성</p><b className={diagnosis.evidenceSufficient?'pass':'warn'}>{diagnosis.evidenceSufficient?'DIAGNOSIS SUFFICIENT':'추가 검증 필요'}</b>{!diagnosis.evidenceSufficient&&diagnosis.assessment?.reasons.map(reason=><p key={reason}>{reason}</p>)}</section></div>
    <section className="diagnosis-submission-summary"><p className="investigation-section-label">제출 결론</p><dl><div><dt>원인 위치</dt><dd>{architectureNode(diagnosis.component)?.label??diagnosis.component}</dd></div><div><dt>문제 유형</dt><dd>{diagnosis.report?.failureType??diagnosis.mechanism}</dd></div><div><dt>핵심 근거</dt><dd>{selected.length}건</dd></div></dl>{solved&&<p>{definition.rootCause.explanation}</p>}{!solved&&<p>현재 확보한 근거가 지지하는 범위까지만 표시합니다. 숨겨진 내부 메커니즘은 공개하지 않습니다.</p>}</section>
    {solved?<section className="post-diagnosis-actions"><p>진단 근거가 충분합니다. 사건을 종료하거나 선택적으로 수정안 회귀 검증을 진행할 수 있습니다.</p><div><button type="button" className="p1-cta-btn" onClick={onNavigateToDebrief}>사건 종료</button><button type="button" onClick={()=>setShowRepair(value=>!value)}>수정안 검증</button></div>{showRepair&&<div className="optional-repair"><p className="investigation-section-label">FAULT → REPAIR → REGRESSION</p><select value={repair} onChange={event=>setRepair(Number(event.target.value) as 0|2|3)}><option value={0}>비율 감소 제거 · 방향별 제한 유지</option><option value={2}>입력 요청 두 배 보상</option><option value={3}>출력 상한 제한 해제</option></select><button type="button" disabled={resolved} onClick={()=>onRunRepair(repair)}>{resolved?'회귀 검증 완료':'수정안 시험 실행'}</button>{repairs.map(run=><details key={run.id}><summary>회귀 시험 #{run.id} · {run.rows.every(row=>row.pass)?'PASS':'FAIL'}</summary><ExperimentResults run={run}/></details>)}</div>}</section>:<section className="wrong-answer-actions"><p>{locationOnly?'원인 위치는 좁혀졌지만 유형을 확정할 만큼 반복 검증되지 않았습니다.':'정답을 바로 공개하지 않습니다. 조사 화면에서 증거 연결을 다시 확인하세요.'}</p><div>{!locationOnly&&<button type="button" onClick={onStartGuidedReview}>조사 해설 보기</button>}<button type="button" className="p1-cta-btn" onClick={onRetryInvestigation}>{locationOnly?'추가 시험으로 돌아가기':'다시 조사하기'}</button></div></section>}
  </div>}

  return <div className="investigation-main-content conclusion-page conclusion-redesign">
    <section className="investigation-page-heading"><p className="investigation-page-title">4 · 결론 제출</p><h2>내가 확인한 근거는 어디까지 말해주나요?</h2>{hypothesis&&<p className="conclusion-hypothesis-inline"><b>현재 가설</b> · {architectureNode(hypothesis.target)?.label??hypothesis.target} — {hypothesis.prediction}</p>}</section>
    <section className="evidence-chain-card primary-verification-evidence"><header><div><p className="investigation-section-label">1 · PRIMARY VERIFICATION EVIDENCE</p><h3>진단을 지지하는 검증 근거</h3></div><span>{selectedPrimary.length}/{verificationEvidence.length}건 선택</span></header><div className="evidence-chain">{verificationEvidence.map(item=><label className={`evidence-chain-item ${item.status.toLowerCase()}`} key={item.id}><input type="checkbox" checked={item.selectedForReport} onChange={event=>onSelectEvidenceForReport(item.id,event.target.checked)}/><span><small>검증 근거 · {item.details?.verificationMethod??'실행 시험'}</small><b>{item.claim}</b><code className="investigation-tech-id">{item.reference.scenarioId??`시험 #${item.reference.runId}`} · {item.details?.designOrigin}</code></span></label>)}{!verificationEvidence.length&&<p className="conclusion-empty-evidence">아직 formal Verification Evidence가 없습니다. Page 3에서 실행 결과를 해석하고 저장하세요.</p>}</div></section>
    <section className="evidence-chain-card supporting-investigation-notes"><header><div><p className="investigation-section-label">2 · SUPPORTING INVESTIGATION NOTES</p><h3>왜 이 대상을 조사했는지 설명하는 메모</h3></div><span>{selectedNotes.length}/{investigationNotes.length}건 첨부</span></header><div className="evidence-chain"><article className="evidence-chain-origin"><small>OBSERVED SYMPTOM</small><strong>{definition.symptom}</strong></article>{orderedNotes.map(item=><label className={`evidence-chain-item ${item.status.toLowerCase()}`} key={item.id}><input type="checkbox" checked={item.selectedForReport} onChange={event=>onSelectEvidenceForReport(item.id,event.target.checked)}/><span><small>{evidenceLabel(item)}</small><b>{item.claim}</b><code className="investigation-tech-id">{item.title}</code></span></label>)}{!investigationNotes.length&&<p className="conclusion-empty-evidence">첨부 가능한 조사 메모가 없습니다.</p>}</div><p className="supporting-note-boundary">조사 메모는 대상 선택의 맥락을 설명하지만 현재 사건의 필수 검증 결과를 대신하지 않습니다.</p></section>
    <section className={`claim-boundary-card ${assessment.sufficient?'supported':'needs-more'}`}><div><p className="investigation-section-label">3 · 현재 근거로 말할 수 있는 범위</p><h3>{assessment.sufficient?'반복되는 검증 결과가 진단을 지지합니다.':'아직 formal 검증 근거가 부족합니다.'}</h3>{supportedComponents.length>0&&<p><b>조사 맥락</b> · {supportedComponents.map(id=>architectureNode(id)?.label??id).join(', ')}에서 저장된 차이가 확인됐습니다.</p>}<p><b>아직 말할 수 없음</b> · 충분한 검증 근거가 있어도 정확한 내부 코드나 숨겨진 계산 메커니즘은 별도 입증 없이는 확정하지 않습니다.</p></div>{!assessment.sufficient&&<ul>{assessment.reasons.map(reason=><li key={reason}>{reason}</li>)}</ul>}</section>
    <div className="conclusion-workspace evidence-first">
      <div className="conclusion-decisions">
        <section className="conclusion-decision-card"><header><div><p className="investigation-section-label">3 · 원인 위치</p><h3>근거가 가리키는 기능 선택</h3></div><span>하나 선택</span></header><div className="cause-location-tree cause-location-cards">{candidateNodes.map(node=><button type="button" key={node.id} aria-pressed={target===node.id} onClick={()=>setTarget(node.id)} title={node.role}><strong>{node.label}</strong><code>{node.id}</code></button>)}</div></section>
        <section className="conclusion-decision-card"><header><div><p className="investigation-section-label">4 · 문제 유형</p><h3>근거가 구분할 수 있는 유형 선택</h3></div><span>하나 선택</span></header><div className="conclusion-failure-types">{failureTypes.map(item=>{const copy=failureCopy[item.id];return <button type="button" key={item.id} aria-pressed={failureType===item.id} onClick={()=>{setFailureType(item.id);setCause('')}} title={copy?.description}><strong>{copy?.title??item.label}</strong><small>{copy?.description}</small></button>})}</div>{detailedUnlocked&&failure&&<fieldset className="detailed-cause-options"><legend>충분한 반복 근거가 있을 때만 선택 가능한 세부 주장</legend>{failure.causes.map(item=><label key={item.id}><input type="radio" name="cause" checked={cause===item.id} onChange={()=>setCause(item.id)}/><span>{item.label}</span></label>)}</fieldset>}</section>
      </div>
      <aside className="conclusion-submit evidence-first-submit"><div><p className="investigation-section-label">5 · 제출 요약</p><dl><div><dt>원인 위치</dt><dd>{target?(architectureNode(target)?.label??target):'미선택'}</dd></div><div><dt>오류 유형</dt><dd>{failureType?(failureCopy[failureType]?.title??failure?.label):'미선택'}</dd></div><div><dt>검증 근거</dt><dd>{selectedPrimary.length}건</dd></div><div><dt>지원 메모</dt><dd>{selectedNotes.length}건</dd></div></dl></div>{!assessment.sufficient&&<p className="submission-boundary-warning">현재 formal 검증 근거의 충분성 규칙을 만족하기 전에는 진단을 확정할 수 없습니다.</p>}{error&&<p role="alert">{error}</p>}<button type="button" className="submit-cta-btn" disabled={!target||!failureType||!selectedPrimary.length||!assessment.sufficient} onClick={submit}>근거 범위 안에서 보고서 제출 →</button>{!assessment.sufficient&&<button type="button" className="report-text-button" onClick={onRetryInvestigation}>추가 검증으로 돌아가기</button>}</aside>
    </div>
  </div>
}
