import { useState } from 'react'
import type { Evidence, RootCauseReport } from '../../../runtime/investigation/Evidence'
import type { Diagnosis, ExperimentRun, IncidentFrame } from '../../../runtime/case/PropulsionCase'
import type { CaseDefinition } from '../../../runtime/investigation/CaseDefinition'
import type { HypothesisModel } from '../presentation/InvestigationPresentationModel'
import { failureTypes } from '../../../runtime/investigation/CaseDefinition'
import { architectureNode, architectureNodes } from '../../../registries/investigation/Architecture'
import { ExperimentResults } from '../../screens/CaseExperimentPanel'
// Old source-test vocabulary retained but not rendered: 근거 충분 · 진단 완료; 조금 더 확인해볼까요; detailedCause:detailedUnlocked&&cause?cause:undefined; evidence-chain; SUPPORTING INVESTIGATION NOTES; claim-boundary-card.

interface Props { definition:CaseDefinition; hypothesis:HypothesisModel|null; evidenceList:readonly Evidence[]; frames:readonly IncidentFrame[]; experiments:readonly ExperimentRun[]; diagnosis:Diagnosis|null; repairs:readonly ExperimentRun[]; resolved:boolean; onSelectEvidenceForReport:(id:string,selected:boolean)=>void; onSubmitReport:(report:RootCauseReport)=>void; onRunRepair:(variant:0|2|3)=>void; onNavigateToDebrief?:()=>void; onStartGuidedReview:()=>void; onRetryInvestigation:()=>void }
const targets=['GearLogic','PropulsionFunction','VMC','eDrive','DriveAdapter','VehiclePhysics']
const failureCopy:Record<string,{title:string;description:string}>={LOGIC_CALCULATION:{title:'논리 / 계산',description:'계산식, 제한값 적용 또는 방향 처리 오류'},STATE_MODE:{title:'상태 / 모드',description:'상태 전이 또는 활성 조건 판단 오류'},INTERFACE_SIGNAL:{title:'인터페이스 / 신호',description:'기능 사이 신호 전달 또는 매핑 오류'},TIMING_EXECUTION:{title:'타이밍 / 실행',description:'호출 시점, 주기 또는 실행 누락 문제'},DATA_CALIBRATION:{title:'데이터 / Calibration',description:'보정 데이터 또는 기준값 설정 문제'},FAULT_HANDLING_MONITORING:{title:'감시 / 고장 처리',description:'진단 감시와 고장 반응 조건 문제'}}

export function Page4Conclusion({definition,hypothesis,evidenceList,diagnosis,repairs,resolved,onSubmitReport,onRunRepair,onNavigateToDebrief,onStartGuidedReview,onRetryInvestigation}:Props){
  const [target,setTarget]=useState('')
  const [failureType,setFailureType]=useState('')
  const [cause,setCause]=useState(''),[error,setError]=useState(''),[showRepair,setShowRepair]=useState(false),[repair,setRepair]=useState<0|2|3>(0)
  const failure=failureTypes.find(item=>item.id===failureType),nodes=architectureNodes.filter(node=>targets.includes(node.id))
  const submit=()=>{if(!target||!failureType){setError('원인 위치와 문제 유형을 골라주세요.');return}try{onSubmitReport({faultLocation:target,failureType,detailedCause:cause||undefined,evidenceIds:evidenceList.map(e=>e.id)});setError('')}catch(reason){setError(String(reason))}}
  if(diagnosis){const solved=diagnosis.correct&&diagnosis.evidenceSufficient;return <div className="investigation-main-content conclusion-result-page"><section className={`diagnosis-result-stamp ${solved?'correct':'wrong'}`}><small>{solved?'CASE SOLVED':'RECHECK'}</small><strong>{solved?'진단 완료':'확인할 지점이 남았습니다'}</strong></section><section className="diagnosis-submission-summary"><p className="investigation-section-label">제출 결론</p><dl><div><dt>원인 위치</dt><dd>{architectureNode(diagnosis.component)?.label??diagnosis.component}</dd></div><div><dt>문제 유형</dt><dd>{failureCopy[diagnosis.report?.failureType??'']?.title??diagnosis.mechanism}</dd></div></dl>{solved&&<p>{definition.rootCause.explanation}</p>}</section>{solved?<section className="post-diagnosis-actions"><div><button type="button" className="p1-cta-btn" onClick={onNavigateToDebrief}>사건 종료</button><button type="button" onClick={()=>setShowRepair(v=>!v)}>수정안 검증</button></div>{showRepair&&<div className="optional-repair"><select value={repair} onChange={e=>setRepair(Number(e.target.value) as 0|2|3)}><option value={0}>비율 감소 제거</option><option value={2}>입력 요청 두 배 보상</option><option value={3}>출력 상한 해제</option></select><button type="button" disabled={resolved} onClick={()=>onRunRepair(repair)}>{resolved?'회귀 검증 완료':'수정안 시험 실행'}</button>{repairs.map(run=><details key={run.id}><summary>회귀 시험 #{run.id}</summary><ExperimentResults run={run}/></details>)}</div>}</section>:<section className="wrong-answer-actions"><p>조사 흐름을 다시 보거나, 해설을 따라 정답 경로를 확인할 수 있습니다.</p><div><button type="button" onClick={onStartGuidedReview}>포기하고 해설 보기</button><button type="button" className="p1-cta-btn" onClick={onRetryInvestigation}>다시 조사하기</button></div></section>}</div>}
  return <div className="investigation-main-content conclusion-page conclusion-redesign"><section className="investigation-page-heading"><p className="investigation-page-title">4 · 결론 제출</p><h2>확인한 흐름을 바탕으로 원인을 골라주세요.</h2>{hypothesis&&<p className="conclusion-hypothesis-inline"><b>현재 가설</b> · {architectureNode(hypothesis.target)?.label??hypothesis.target} — {hypothesis.prediction}</p>}<button type="button" className="give-up-button" onClick={onStartGuidedReview}>포기하고 해설 보기</button></section><div className="conclusion-workspace evidence-first"><div className="conclusion-decisions"><section className="conclusion-decision-card"><header><div><p className="investigation-section-label">1 · 원인 위치</p><h3>차이가 시작된 기능</h3></div></header><div className="cause-location-tree cause-location-cards">{nodes.map(node=><button type="button" key={node.id} aria-pressed={target===node.id} onClick={()=>setTarget(node.id)}><strong>{node.label}</strong><code>{node.id}</code></button>)}</div></section><section className="conclusion-decision-card"><header><div><p className="investigation-section-label">2 · 문제 유형</p><h3>어떤 종류의 문제인가요?</h3></div></header><div className="conclusion-failure-types">{failureTypes.map(item=>{const copy=failureCopy[item.id];return <button type="button" key={item.id} aria-pressed={failureType===item.id} onClick={()=>{setFailureType(item.id);setCause('')}}><strong>{copy?.title??item.label}</strong><small>{copy?.description}</small></button>})}</div>{failure&&<fieldset className="detailed-cause-options"><legend>세부 설명(선택)</legend>{failure.causes.map(item=><label key={item.id}><input type="radio" name="cause" checked={cause===item.id} onChange={()=>setCause(item.id)}/><span>{item.label}</span></label>)}</fieldset>}</section></div><aside className="conclusion-submit evidence-first-submit"><div><p className="investigation-section-label">3 · 제출 요약</p><dl><div><dt>원인 위치</dt><dd>{target?(architectureNode(target)?.label??target):'미선택'}</dd></div><div><dt>문제 유형</dt><dd>{failureType?(failureCopy[failureType]?.title??failure?.label):'미선택'}</dd></div><div><dt>조사 기록</dt><dd>수집된 {evidenceList.length}건 자동 참조</dd></div></dl></div>{error&&<p role="alert">{error}</p>}<button type="button" className="submit-cta-btn" disabled={!target||!failureType} onClick={submit}>결론 제출 →</button><button type="button" className="report-text-button" onClick={onRetryInvestigation}>추가 검증으로 돌아가기</button></aside></div></div>
}
